//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int?
    public var uuid: String?
    public var fullName: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var avatarUrl: String?
    public var phone: String?
    public var accessToken: String?

    public init(_id: Int?, uuid: String?, fullName: String?, email: String?, avatarUrl: String?, phone: String?, accessToken: String?) {
        self._id = _id
        self.uuid = uuid
        self.fullName = fullName
        self.email = email
        self.avatarUrl = avatarUrl
        self.phone = phone
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case uuid
        case fullName = "full_name"
        case email
        case avatarUrl = "avatar_url"
        case phone
        case accessToken = "access_token"
    }

}

